### ISSUE TITLE
TMAlign/APoc results to UniProt metadata information.

### ISSUE THREAD

**Issue by rbdavid** [BSDExabio/structural_DLFA#72]
We have TMAlign/APoc results files (whether parsed or not). Need to pull the PDB IDs associated with top hits, grab the respective UniProt IDs. With a UniProt ID, we need to gather the metadata file from UniProt's API, parse that information, and store for later use. 

"Later use" being comparison to sequence alignment results (hhblits, SAdLSA) from a variety of sequence databases, which all have different information associated with them (a whole 'nother problem).

**Comment by markcoletti** [comment]
Tentative high-level tasking:

1. Do a "pre-processing" step to pull in data and possibly create one or more new tables in the database
2. Jupyter notebook to work out integrating database data with pulling down data from web sites
3. After working out a stable workflow in the notebook, codify that into a standalone script-based implementation

So, one of the next iterations on this task is to work out the details, particularly of the first step.

**Comment by rbdavid** [comment]
Fixed bugs in the apoc_parsers.py module file, specifically in the score file parsing function.

**Comment by rbdavid** [comment]
Have a uniprot query tool to pull most of the metadata from the flat txt file associated with a uniprot ID. Combining the tools now.

**Comment by rbdavid** [comment]
Code break down: 
1) For every protein model's structural alignment, parse the APoc/TMalign score file to get PDB IDs.
2) Collect all the PDB ID lists and get the unique PDB IDs. Run the RCSB request function to pull the relevant Uniprot accession codes. Avoid redundant request calls to the RCSB query tool by only pulling unique PDB IDs. 
3) Collect the unique Uniprot accession IDs. Request the flat files associated with these Uniprot IDs and parse them. 

We could joblib/dask-ify each of these steps but step 2 needs to wait for step 1 to completely finish so that we can gather all unique PDB IDs (to avoid redundant request calls). Similarly, step 2 needs to finish before we should attempt step 3.

**Comment by rbdavid** [comment]
Just a note: all of this work has been in a jupyter notebook so far. I need to gather the codes into a module file and push to the github.

**Comment by rbdavid** [comment]
Push a basic module file associated with the function to request and parse a UniProt flat file.

**Comment by rbdavid** [comment]
Fixed a bug in the code. Finished the most basic version of a dask workflow. Might need to refactor or update. Testing truly begins now though.

**Comment by rbdavid** [comment]
@markcoletti Having an issue with implementing the rcsb_query functions in my dask workflow that is running on Andes. After some debugging, here's the error that is being thrown: 

`Traceback (most recent call last):
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f88a0407d30>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.rcsb.org', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88a0407d30>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/alpine/bif135/proj-shared/rbd_work/dask_testing/parsing_results/testing_rcsb_query.py", line 40, in <module>
    uniprotid = rcsb_query.query_uniprot_str(pdbid_chainid)
  File "/gpfs/alpine/bif135/proj-shared/rbd_work/scripts/git/structural_DLFA/parsers/rcsb_query.py", line 37, in query_uniprot_str
    return query_uniprot(protein, chain)
  File "/gpfs/alpine/bif135/proj-shared/rbd_work/scripts/git/structural_DLFA/parsers/rcsb_query.py", line 51, in query_uniprot
    r = requests.post('https://data.rcsb.org/graphql',
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/ccs/home/davidsonrb/Apps/miniconda3_ANDES/envs/openmm_andes/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data.rcsb.org', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88a0407d30>: Failed to establish a new connection: [Errno 110] Connection timed out'))`

**Comment by rbdavid** [comment]
The rcsb_query functions work great on my local desktop and on the Slate jupyterhub. I worry this is an issue of OLCF blocking any queries to an external databases. Is this a logical conclusion? I can't seem to find any statements in the documentation that querying databases is prevented.

**Comment by rbdavid** [comment]
Still no response from OLCF help. :(

**Comment by rbdavid** [comment]
Code is working to access both the RCSB graphql query and UniProt REST API for metadata. Per the request of OLCF help desk, I will not push the code that fixed this issue. But, the fix had something to do with setting bash proxy environment variables.

**Comment by rbdavid** [comment]
Code is finished but hasn't been pushed to github. Amending that now.

**Comment by rbdavid** [comment]
Code pushed. Closing and pushing to main branch.
